name: SDLC - Develop push

on:
  push:
    branches:
      - develop

jobs:
  docker-build-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push develop image
        run: |
          docker build -t ${{ vars.DOCKERHUB_ORGANIZATION }}/sldc-test:develop .
          docker push ${{ vars.DOCKERHUB_ORGANIZATION }}/sldc-test:develop
