trigger: none
pr: none
resources:
  repositories: []
  
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: "ubuntu-latest"
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"